### PR TITLE
Added option for custom history table name

### PR DESCRIPTION
**Pull request by kurisutofu**
- Added 'modelSuffix' to options in order to give the ability to choose the historical model and table names.
- Added 3 test groups to test with different modelSuffix
- Update test structure to have newDB function with options to facilitate addition of new tests
- Updated ReadMe file to reflect the new options with examples

### CODE REVIEW

**Comment by znarf** [comment]
@kurisutofu Thank you for sharing this!

I decided to name this fork `sequelize-historical` (I add to differentiate it from `sequelize-temporal`)   and I would like to keep that 'historical' word in the documentation. I can't accept the PR in that state.

I just merged the lodash4 PR that you also added to this PR, this is why there is a conflict now.

**Comment by kurisutofu** [comment]
Hi @znarf ,

Yes, sorry, I renamed it and published it as a separate npm module because my first PR was 2 weeks ago and I needed it in a project so I could not wait.

The PR was supposed to be only to add the possibility to choose the historical table suffix.
The rest I added were functions I wanted in my project so not sure it's interesting for you.
I think all my commits were grouped to the same PR though.

Not sure if it's an automation issue or something I did wrong ... (first time contributing on GitHub)

**Comment by znarf** [comment]
@kurisutofu would be great to mutualize the work and don't have multiple forks.

If you want me to integrate you work, please edit the PR (or create a new one), make sure there is only the changes you want to be merged.

**Comment by kurisutofu** [comment]
Hi, I updated the name back and will create a new PR.

**Comment by kurisutofu** [comment]
@znarf Can you please look at merging the other PR I opened?
I need to use this in my project and it's been 2 weeks it is pending now.

**Comment by kurisutofu** [comment]
@znarf , can you please merge the other PR?
Or should I revert to using it under a different name?

**Pull request closed without merging**
